import axios from "axios";

export const texts = {
  uzbek: {
    total: "Umumiy son",
    active: "Faollar",
    inactive: "Nofaollar",
    confirmDelete: "Hammasini o'chirishni tasdiqlaysizmi?",
    deleteAll: "Hammasini ochirish",
    id: "ID",
    name: "Nomi",
    price: "Narx",
    count: "Mahsulot Soni",
    address: "Manzil",
    status: "Status",
    customer: "Mijoz",
    delete: "O'chirish",
  },
  english: {
    total: "Total",
    active: "Active",
    inactive: "Inactive",
    confirmDelete: "Are you sure you want to delete everything?",
    deleteAll: "Delete All",
    id: "ID",
    name: "Name",
    price: "Price",
    count: "Product Count",
    address: "Address",
    status: "Status",
    customer: "Customer",
    delete: "Delete",
  },
  russian: {
    total: "Всего",
    active: "Активные",
    inactive: "Неактивные",
    confirmDelete: "Вы уверены, что хотите все удалить?",
    deleteAll: "Удалить все",
    id: "ID",
    name: "Имя",
    price: "Цена",
    count: "Количество продуктов",
    address: "Адрес",
    status: "Статус",
    customer: "Клиент",
    delete: "Удалить",
  },
};

